### ISSUE TITLE
Store the profile in a global reactive object

### ISSUE THREAD

**Issue by DarkLite1** [darrenjennings/guuu.io#11]
You could also create a composition function that you call within the setup method and keep this line out of the exported function so the state is global and not local to the function. 

`const profile = ref([])`

Look here for an example: https://vueschool.io/articles/vuejs-tutorials/state-management-with-composition-api/

**Comment by darrenjennings** [comment]
Yes! This is true, I like the “no vuex” approach. useSWRV could be used in your useProduct composable which would alleviate the burden of caching/error/loading/deduplication/state management.

**Comment by DarkLite1** [comment]
Indeed, it takes away all those concerns if you just keep it in a reactive property. Maybe you should add a small reference to this in the article so people know there's another (maybe better) way.
