### ISSUE TITLE
Please add RSS feed

### ISSUE THREAD

**Issue by nitinthewiz** [darrenjennings/guuu.io#5]
Hey Darren,

I found Awesome Personal blogs and realized there's no RSS feed list (OPML file) in the repo, so I'm adding one. I noticed that your blog doesn't have an RSS feed, simply because you've not added the feed plugin to it.

I found that the way to do it is pretty simple - https://github.com/webmasterish/vuepress-plugin-feed

Could you please add a feed and then update the OPML file? (I've not submitted it yet to the awesome personal blogs repo, will do it soon)

**Comment by darrenjennings** [comment]
@nitinthewiz would welcome a PR!
